apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "thumbor.fullname" . }}
  labels:
    {{- include "thumbor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thumbor.selectorLabels" . | nindent 6 }}
  {{- if (eq .Values.kind "StatefulSet") }}
  serviceName: {{ include "thumbor.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "thumbor.fullname" .}}-data
        labels:
          {{- include "thumbor.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.pvc.accessModes | nindent 10 }}
        storageClassName: {{ .Values.pvc.storageClassName }}
        resources:
          {{- toYaml .Values.pvc.claim.resources | nindent 10 }}
        {{- if .Values.pvc.volumeName }}
        volumeName: {{ .Values.pvc.volumeName }}
        {{- end }}
        {{- with .Values.pvc.dataSource }}
        dataSource:
          {{- toYaml . | nindent 8 }}
        {{ end }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "thumbor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thumbor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.pvc.enabled }}
      volumes:
        - name: thumbor-data
          persistentVolumeClaim:
            claimName: {{ include "thumbor.fullname" . }}-data
      {{- else if .Values.pvc.existingClaim }}
      volumes:
        - name: thumbor-data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.pvc.existingClaim .) }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ include "helpers.create-env-list" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.pvc.enabled }}
          volumeMounts:
            - name: thumbor-data
              mountPath: {{ .Values.pvc.mountPath }}
          {{ end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
