{{- if and (.Values.pvc.enabled) (eq .Values.kind "Deployment") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thumbor.fullname" . }}-data
  labels:
    {{- include "thumbor.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    {{- toYaml .Values.pvc.claim.resources | nindent 4 }}
  {{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName }}
  {{- end }}
{{- end }}
