apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.containerEnv.secret.name }}
  labels:
    {{- include "thumbor.labels" . | nindent 8 }}
type: Opaque
data:
  {{- range $key, $val := .Values.containerEnv.secret.env }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
